name: Deploy Fractal Play

on:
    push:
        branches:
            - trunk

jobs:
    deploy:

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - run: npm install --global elm-tooling

            - name: Copy static files
              run: mkdir -p dist && cp -r public/* dist/

            - name: Build
              run: npx elm make src/Main.elm --output=dist/fractal-play.js
            
            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                path: dist
            
            - name: Deploy
              uses: actions/deploy-pages@v4

              

